#!/bin/bash


#only works in Linux, but I don't need to be portable here.
#MY_EXE=`readlink -f $0`
#MY_DIR=`dirname ${MY_EXE}`
MY_DIR=/Users/gsymons/dotfiles

echo Discovered install directory: ${MY_DIR}

SETTINGS_FILE=${MY_DIR}/install_settings.cfg

if [[ -f ${SETTINGS_FILE} ]]; then
    echo Loading local settings from ${SETTINGS_FILE}
    . ${SETTINGS_FILE}
fi

# FILE[;DEST]
LN_FILES="${LN_FILES} 
            .vimrc 
            .vim 
            .bash_aliases 
            .bash_aliases.local 
            .gitconfig 
            .git_aliases
            gitignore;.gitignore
            .autotest
            subversion/config;.subversion/config
            .hgrc"

for file_spec in ${LN_FILES}; do
    src_file=$(echo $file_spec | cut -f1 -d';')
    dst_file=$(echo $file_spec | cut -f2 -d';')

    full_path=${MY_DIR}/$src_file
    if [[ -e $full_path ]]; then
        echo Symlinking $full_path to ~/$dst_file
        if [[ ! -d `dirname $dst_file` ]]; then
            mkdir -p `dirname $dst_file`
        fi
        rm -f ~/$dst_file
        ln -s $full_path ~/$dst_file
    fi
done
